stages:
  - build
  - test
  - build-docker
  - deploy-manifest

variables:
  IMAGE_PATH: ${CI_REGISTRY}/${CI_PROJECT_PATH}

build:
  image: golang:1.5
  script:
    - curl https://glide.sh/get | sed 's+get TAG https://glide.sh/version+TAG=v0.12.3+' | sh
    - glide install -v
    - make binary-linux-amd64
    - chmod +x bin/linux/amd64/local-persist
  artifacts:
    paths:
      - bin

test:
  image: docker:dind
  services:
    - docker:dind
  script:
    - apk add --no-cache make
    - bin/linux/amd64/local-persist &
    - scripts/integration.sh
    - make test

.build-docker:
  image: docker:latest
  services:
    - docker:dind
  stage: build-docker
  only:
#    refs:
#      - master
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t local-persist:$DOCKER_ARCH --build-arg GOARCH=$DOCKER_GOARCH --build-arg GOARM=$DOCKER_GOARM .
    - docker tag local-persist:$DOCKER_ARCH $IMAGE_PATH:latest-$DOCKER_ARCH
    - docker push $IMAGE_PATH:latest-$DOCKER_ARCH
    #- docker tag local-persist:$DOCKER_ARCH $IMAGE_PATH:$TRAVIS_TAG-$DOCKER_ARCH
    #- docker push $IMAGE_PATH:$TRAVIS_TAG-$DOCKER_ARCH
  variables:
    - DOCKER_ARCH: amd64
    - DOCKER_GOARCH: amd64

build-armv6:
  extends: .build-docker
  variables:
    DOCKER_ARCH: arm32v6
    DOCKER_GOARCH: arm
    DOCKER_GOARM: 6

build-armv7:
  extends: .build-docker
  variables:
    DOCKER_ARCH: arm32v7
    DOCKER_GOARCH: arm
    DOCKER_GOARM: 7

build-arm64:
  extends: .build-docker
  variables:
    DOCKER_ARCH: aarch64
    DOCKER_GOARCH: arm64

deploy-manifest:
  stage: deploy-maifest
  only:
    - master
    - tags
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - export TAG=${CI_COMMIT_TAG:-latest}
    - envsubst < manifest.template.yml > manifest.yml
    - curl -fsSL https://github.com/estesp/manifest-tool/releases/download/v0.7.0/manifest-tool-linux-amd64 > ./manifest-tool
    - chmod +x ./manifest-tool
    - ./manifest-tool push from-spec manifest.yml
